config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  resources :restaurants, only: %i[index show new create destroy] do
    resources :reviews, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  STRONG_PARAMS = %i[
    name
    street
    city
    country
  ]
  has_many :reviews

  geocoded_by :address

  # This is going to make the address be saved before geocoding
  before_validation :generate_and_save_address
  # This is going to make geocode run after validation
  # Check AR callbacks -> https://guides.rubyonrails.org/active_record_callbacks.html
  after_validation :geocode

  def generate_and_save_address
     self.address = "#{street}, #{city}, #{country}"
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    set_restaurant
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new strong_params
    @restaurant.save ? redirect_to(@restaurant) : render(:new)
  end

  def destroy
    set_restaurant
    @restaurant.destroy
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def strong_params
    params.require(:restaurant).permit(Restaurant::STRONG_PARAMS)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<%= link_to "Create a Restaurant", new_restaurant_path %>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
      <%= link_to '❌', restaurant, method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
  
  <%= f.input :name %>
  <%= f.input :street %>
  <%= f.input :city %>
  <%= f.input :country, as: :string %>

  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<%= link_to "Home", root_path %>

<h1><%= @restaurant.name %> <small><%= @restaurant.address %></small></h1>
<h2>
  <%= pluralize @restaurant.reviews.size, "review" %>
</h2>

<div id="reviews">
  <% if @restaurant.reviews.blank? %>
    Be the first to leave a review for <%= @restaurant.name %>
  <% else %>
    <% @restaurant.reviews.each do |review| %>
      <p><%= review.content %></p>
    <% end %>
  <% end %>
</div>

<%= simple_form_for([ @restaurant, @review ]) do |f| %>
  <%= f.input :content, as: :text %>
  <%= f.button :submit %>
<% end %>